version: "3.9"

services:
  laravel:
    image: laravel-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage/app/public:/var/www/html/storage/app/public
      # ./backend/public/storage sera créé par le lien symbolique
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  react:
    image: react-vite-app
    build:
      context: ./vue
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "5173:5173"
    volumes:
      - ./vue:/app
      - /app/node_modules
    environment:
    - VITE_API_URL=https://miam-miam-q5x4.onrender.com/
    - CHOKIDAR_USEPOLLING=true